# Generated by Django 4.1.6 on 2023-02-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': [-1]},
        ),
    ]
